<?php
/**
 * Cecropia Favico Extension
 *
 * NOTICE OF LICENSE
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * @version     1.0.0
 * @category    Cecropia
 * @package     Cecropia_Favico
 * @author      Mohammed NAHHAS <m.nahhas@live.fr>
 * @copyright   Copyright (c) 2014 Mohammed NAHHAS
 * @licence     OSL - Open Software Licence 3.0
 *
 */

/**
 * Main template
 * @class Cecropia_Favico_Block_Main
 */
?>

<?php $cartQty = $this->getCartTotalQty(); ?>

<?php if ($this->isEnabled() && ($cartQty > 0)) : ?>
    <script>
        $j(document).ready(function() {
            var badge = <?php echo $cartQty; ?>;
            var favicon = new Favico({
                bgColor : '<?php echo $this->getBgColor(); ?>',
                textColor : '<?php echo $this->getTextColor(); ?>',
                fontFamily : '<?php echo $this->getFontFamily(); ?>',
                fontStyle : '<?php echo $this->getFontStyle(); ?>',
                type : '<?php echo $this->getType(); ?>',
                position : '<?php echo $this->getPosition(); ?>',
                animation : '<?php echo $this->getAnimation(); ?>'
            });

            favicon.badge(badge);
        });
    </script>
<?endif; ?>